Repository spinnaker/buildtool, pull requests merged in 2020-03, with the labels that each got.

#34 feat(builds): add a script to build containers outside of GCB
  build-service-container.sh
Labels: ready-to-merge

#35 fix(kubernetes): Actually fix race condition in V2 deployment
  dev/validate_bom__deploy.py
Labels: ready-to-merge

#43 chore(buildtool): Auto-deprecate old Spinnaker versions
  dev/buildtool/changelog_commands.py
Labels: ready-to-merge

#72 fix(halyard release): ignore invalid lines from `gsutil cat`
  dev/buildtool/halyard_commands.py
  dev/buildtool/subprocess_support.py
Labels: ready to merge

#75 chore(containers): don't save the cache until the end
  dev/buildtool/cloudbuild/containers-build-java8.yml
  dev/buildtool/cloudbuild/containers-tag-java8.yml
Labels: auto merged, ready to merge

#80 chore(buildtool): Add function to get next patch parameters
  dev/buildtool/spinnaker_commands.py
Labels: ready to merge
